rosalindfranklininstitute/rfi-file-monitor

rfi_file_monitor/applicationwindow.py, rfi_file_monitor/file.py, rfi_file_monitor/operation.py, rfi_file_monitor/operations/dummy_operation.py, rfi_file_monitor/operations/s3_uploader.py, rfi_file_monitor/utils.py, setup.py, test-file-writer.py
=> Add S3Upload operation

README.md, environment.yml
@LAShemilt please give these a try
=> Add installation instructions

environment.yml, rfi_file_monitor/applicationwindow.py, rfi_file_monitor/operations/s3_uploader.py, rfi_file_monitor/operations/sftp_uploader.py, rfi_file_monitor/utils.py, setup.py
Closes #18
Also: put in a check to ensure that params cannot be overwritten
=> SftpUploaderOperation: new operation

rfi_file_monitor/application.py, rfi_file_monitor/applicationwindow.py, setup.py
=> Use importlib instead of pkg_resources

rfi_file_monitor/application.py, rfi_file_monitor/data/menus-appmenu.ui, rfi_file_monitor/data/menus-common.ui, rfi_file_monitor/data/rfi-instruments.yaml, rfi_file_monitor/preferences.py, rfi_file_monitor/preferenceswindow.py, rfi_file_monitor/utils.py, setup.py
@LAShemilt I got it working for booleans... will look into comboboxes now
=> PreferencesWindow: add window to manage preferences

rfi_file_monitor/applicationwindow.py, rfi_file_monitor/file.py, rfi_file_monitor/operation.py, rfi_file_monitor/operations/dummy_operation.py, rfi_file_monitor/operations/local_copier.py, rfi_file_monitor/operations/s3_uploader.py, rfi_file_monitor/operations/sftp_uploader.py, rfi_file_monitor/utils.py, setup.py
=> Allow tagging registered widgets as non-exportable

.github/workflows/publish-to-pypi.yml, setup.py
=> Create initial release

environment.yml, rfi_file_monitor/__init__.py, rfi_file_monitor/application.py, rfi_file_monitor/applicationwindow.py, rfi_file_monitor/file.py, rfi_file_monitor/operations/dummy_operation.py, rfi_file_monitor/operations/local_copier.py, rfi_file_monitor/operations/s3_uploader.py, rfi_file_monitor/operations/sftp_uploader.py, rfi_file_monitor/preferenceswindow.py, rfi_file_monitor/utils.py, setup.cfg, test-file-writer.py
=> Add support for Bugsnag

rfi_file_monitor/applicationwindow.py, rfi_file_monitor/utils.py
=> Add support for monitoring exclusively certain file types and extensions

rfi_file_monitor/application.py
=> Fix unhandled exception when no preferences have been registered

rfi_file_monitor/operations/s3_uploader.py, rfi_file_monitor/utils/widgetparams.py
=> Stop misusing placeholder in entries

rfi_file_monitor/operations/dummy_operation.py, rfi_file_monitor/operations/s3_uploader.py
=> S3Uploader: allow setting ACLS for buckets and objects through pre-flight metadata

rfi_file_monitor/operations/s3_uploader.py, rfi_file_monitor/utils/__init__.py
=> Add utility methods to easily find metadata

rfi_file_monitor/operations/s3_uploader.py
=> S3Uploader: restrict boto3 client lifetime to methods it is used in

conda-build/meta.yaml, rfi_file_monitor/operations/sftp_uploader.py, rfi_file_monitor/utils/__init__.py
=> Refactor SSH operation

conda-build/meta.yaml, rfi_file_monitor/applicationwindow.py, rfi_file_monitor/file.py, rfi_file_monitor/job.py, rfi_file_monitor/operations/dummy_operation.py
=> Makes failures clear using red row backgrounds and messages in tooltips

rfi_file_monitor/applicationwindow.py, rfi_file_monitor/file.py
=> Add option to delay status promotion from saved to queued

rfi_file_monitor/applicationwindow.py, rfi_file_monitor/file.py, rfi_file_monitor/operations/dummy_operation.py, test-file-writer.py
=> Enforce delayed saves and monitor multiple saves

rfi_file_monitor/operations/local_copier.py, rfi_file_monitor/operations/s3_uploader.py, rfi_file_monitor/operations/sftp_uploader.py
=> Skipped operations should still attach metadata

conda-build/meta.yaml, environment.yml, rfi_file_monitor/applicationwindow.py, rfi_file_monitor/operations/dropbox_uploader.py, setup.cfg
=> DropboxUploaderOperation: new operation

rfi_file_monitor/applicationwindow.py
=> Disable remove operations button during run

rfi_file_monitor/applicationwindow.py
=>  added extra information for allowed and ignored

rfi_file_monitor/applicationwindow.py, rfi_file_monitor/file.py
=> Add support for requeueing files after resaves

rfi_file_monitor/application.py, rfi_file_monitor/applicationwindow.py, rfi_file_monitor/data/filter-popover.ui, rfi_file_monitor/utils/__init__.py
=> ApplicationWindow: allow filtering files by name and status

rfi_file_monitor/applicationwindow.py
=> ApplicationWindows: Add output status bar

conda-build/meta.yaml, rfi_file_monitor/operations/sftp_uploader.py, rfi_file_monitor/utils/__init__.py, setup.cfg
=> Retry failed sftp uploads

rfi_file_monitor/applicationwindow.py
=> Fix patterns entry sensitivity during run

conda-build/meta.yaml, rfi_file_monitor/application.py, rfi_file_monitor/applicationwindow.py, rfi_file_monitor/engine.py, rfi_file_monitor/engine_advanced_settings.py, rfi_file_monitor/engines/file_watchdog_engine.py, rfi_file_monitor/engines/file_watchdog_engine_advanced_settings.py, rfi_file_monitor/engines/temporary_file_engine.py, rfi_file_monitor/file.py, rfi_file_monitor/job.py, rfi_file_monitor/operation.py, rfi_file_monitor/operations/dropbox_uploader.py, rfi_file_monitor/operations/dummy_operation.py, rfi_file_monitor/operations/local_copier.py, rfi_file_monitor/operations/s3_uploader.py, rfi_file_monitor/operations/sftp_uploader.py, rfi_file_monitor/preferenceswindow.py, rfi_file_monitor/queue_manager.py, rfi_file_monitor/utils/__init__.py, rfi_file_monitor/utils/decorators.py, rfi_file_monitor/utils/exceptions.py, rfi_file_monitor/utils/paramswindow.py, rfi_file_monitor/utils/widgetparams.py, setup.cfg
=> Turn monitoring mechanism into plugins

.github/workflows/ci.yml, MANIFEST.in, conda-build/meta.yaml, rfi_file_monitor/application.py, rfi_file_monitor/applicationwindow.py, rfi_file_monitor/docs/queue_manager.pango, rfi_file_monitor/engines/docs/file_watchdog_engine.pango, rfi_file_monitor/engines/docs/template.pango, rfi_file_monitor/engines/docs/temporary_file_engine.pango, rfi_file_monitor/engines/file_watchdog_engine.py, rfi_file_monitor/engines/temporary_file_engine.py, rfi_file_monitor/operation.py, rfi_file_monitor/operations/docs/dropbox_uploader.pango, rfi_file_monitor/operations/docs/dummy_operation.pango, rfi_file_monitor/operations/docs/local_copier.pango, rfi_file_monitor/operations/docs/s3_uploader.pango, rfi_file_monitor/operations/docs/sftp_uploader.pango, rfi_file_monitor/operations/docs/template.pango, rfi_file_monitor/operations/dropbox_uploader.py, rfi_file_monitor/operations/dummy_operation.py, rfi_file_monitor/operations/local_copier.py, rfi_file_monitor/operations/s3_uploader.py, rfi_file_monitor/operations/sftp_uploader.py, rfi_file_monitor/queue_manager.py, rfi_file_monitor/utils/__init__.py, rfi_file_monitor/utils/decorators.py, rfi_file_monitor/utils/helpwindow.py, rfi_file_monitor/utils/paramswindow.py
=> Add help button for engines

.github/workflows/ci.yml, rfi_file_monitor/applicationwindow.py
=> _files_tree_model_visible_func: fix unhandled exception

rfi_file_monitor/engines/file_watchdog_engine.py, rfi_file_monitor/file.py, rfi_file_monitor/job.py, rfi_file_monitor/operations/sftp_uploader.py, rfi_file_monitor/utils/__init__.py, setup.cfg
=> SftpUploader: add support for chmod

conda-build/meta.yaml, rfi_file_monitor/application.py, rfi_file_monitor/applicationwindow.py, rfi_file_monitor/engines/aws_s3_bucket_engine.py, rfi_file_monitor/engines/aws_s3_bucket_engine_advanced_settings.py, rfi_file_monitor/engines/docs/aws_s3_bucket_engine.pango, rfi_file_monitor/file.py, rfi_file_monitor/operations/docs/dummy_operation.pango, rfi_file_monitor/operations/docs/s3_copier.pango, rfi_file_monitor/operations/docs/s3_downloader.pango, rfi_file_monitor/operations/docs/s3_uploader.pango, rfi_file_monitor/operations/docs/sftp_uploader.pango, rfi_file_monitor/operations/dropbox_uploader.py, rfi_file_monitor/operations/s3_copier.py, rfi_file_monitor/operations/s3_downloader.py, rfi_file_monitor/operations/s3_uploader.py, rfi_file_monitor/utils/__init__.py, rfi_file_monitor/utils/s3.py, rfi_file_monitor/utils/widgetparams.py, setup.cfg
=> Add operation for downloading S3 objects

.bumpversion.cfg, .github/workflows/ci.yml, conda-build/meta.yaml, rfi_file_monitor/__init__.py, rfi_file_monitor/application.py, rfi_file_monitor/applicationwindow.py, rfi_file_monitor/job.py, rfi_file_monitor/utils/googleanalytics.py, rfi_file_monitor/version.py
=> Add support for Google Analytics usage tracking

conda-build/meta.yaml, setup.cfg
See https://github.com/rosalindfranklininstitute/rfi-file-monitor/issues/152
=> Add pathtools as an explicit dependency

.vscode/settings.json, rfi_file_monitor/engines/directory_watchdog_engine.py, rfi_file_monitor/engines/directory_watchdog_engine_advanced_settings.py, rfi_file_monitor/engines/docs/directory_watchdog_engine.pango, rfi_file_monitor/file.py, rfi_file_monitor/utils/__init__.py, rfi_file_monitor/utils/decorators.py
=> DirectoryWatchdogEngine: distinguish between patterns for files and directories

conda-build/meta.yaml, rfi_file_monitor/job.py, rfi_file_monitor/operations/directory_compressor.py, rfi_file_monitor/operations/docs/directory_compressor.pango, setup.cfg
=> DirectoryCompressor: new operation

conda-build/meta.yaml, rfi_file_monitor/__init__.py, rfi_file_monitor/application.py, rfi_file_monitor/applicationwindow.py, rfi_file_monitor/data/models/s3/2006-03-01/service-2.sdk-extras.json, rfi_file_monitor/engine.py, rfi_file_monitor/engines/aws_s3_bucket_engine.py, rfi_file_monitor/engines/aws_s3_bucket_engine_advanced_settings.py, rfi_file_monitor/engines/base_s3_bucket_engine.py, rfi_file_monitor/engines/ceph_s3_bucket_engine.py, rfi_file_monitor/engines/ceph_s3_bucket_engine_advanced_settings.py, rfi_file_monitor/engines/docs/aws_s3_bucket_engine.pango, rfi_file_monitor/engines/docs/ceph_s3_bucket_engine.pango, rfi_file_monitor/file.py, rfi_file_monitor/operation.py, rfi_file_monitor/operations/dummy_operation.py, rfi_file_monitor/queue_manager.py, rfi_file_monitor/utils/decorators.py, rfi_file_monitor/utils/googleanalytics.py, setup.cfg
=> CepS3BucketEngine: new class

rfi_file_monitor/operations/s3_downloader.py, rfi_file_monitor/operations/s3_uploader.py, rfi_file_monitor/utils/s3.py
=> S3(Down|Up)loader: add tenacity decorator to retry

rfi_file_monitor/application.py, rfi_file_monitor/applicationwindow.py, rfi_file_monitor/engines/temporary_file_engine.py, rfi_file_monitor/operations/dummy_operation.py, rfi_file_monitor/preferences.py, rfi_file_monitor/preferenceswindow.py
=> Preferences: allow excluding operations and engines

rfi_file_monitor/application.py, rfi_file_monitor/engine.py, rfi_file_monitor/engines/aws_s3_bucket_engine.py, rfi_file_monitor/engines/base_s3_bucket_engine.py, rfi_file_monitor/engines/ceph_s3_bucket_engine.py, rfi_file_monitor/engines/directory_watchdog_engine.py, rfi_file_monitor/engines/file_watchdog_engine.py, rfi_file_monitor/engines/temporary_file_engine.py, rfi_file_monitor/engines/urls_engine.py, rfi_file_monitor/preferences.py, rfi_file_monitor/utils/__init__.py, setup.cfg
=> (FileWatchdog|AWSS3Bucket)Engine: add preference for global ignored/allowed patterns

rfi_file_monitor/__init__.py, rfi_file_monitor/application.py, rfi_file_monitor/applicationwindow.py, rfi_file_monitor/engine.py, rfi_file_monitor/engines/aws_s3_bucket_engine.py, rfi_file_monitor/engines/base_s3_bucket_engine.py, rfi_file_monitor/engines/ceph_s3_bucket_engine.py, rfi_file_monitor/engines/directory_watchdog_engine.py, rfi_file_monitor/engines/file_watchdog_engine.py, rfi_file_monitor/engines/temporary_file_engine.py, rfi_file_monitor/engines/urls_engine.py, rfi_file_monitor/file.py, rfi_file_monitor/operations/directory_compressor.py, rfi_file_monitor/operations/dropbox_uploader.py, rfi_file_monitor/operations/dummy_operation.py, rfi_file_monitor/operations/local_copier.py, rfi_file_monitor/operations/s3_uploader.py, rfi_file_monitor/operations/sftp_uploader.py, rfi_file_monitor/operations/url_downloader.py, rfi_file_monitor/preferenceswindow.py, rfi_file_monitor/queue_manager.py, rfi_file_monitor/utils/__init__.py, rfi_file_monitor/utils/decorators.py, rfi_file_monitor/utils/googleanalytics.py, rfi_file_monitor/utils/widgetparams.py
=> Cleanup logger.debug statements

rfi_file_monitor/engines/directory_watchdog_engine.py, rfi_file_monitor/engines/file_watchdog_engine.py
=> (File|Directory)WatchdogEngine: fix bug

rfi_file_monitor/applicationwindow.py, rfi_file_monitor/operation.py, rfi_file_monitor/operations/s3_uploader.py
If a bucket was created during the preflight_check, it will now be
deleted during the preflight_cleanup
=> S3Uploader: use preflight_cleanup

conda-build/meta.yaml, setup.cfg
This package is used in the URLParser
=> Add missing dependency python-dateutil

rfi_file_monitor/engines/directory_watchdog_engine_advanced_settings.py, rfi_file_monitor/operations/s3_uploader.py
=> S3Uploader: add support for bucket CORS config

rfi_file_monitor/applicationwindow.py, rfi_file_monitor/utils/__init__.py
=> Turn list of operations into Gtk.ListBox

conda-build/meta.yaml, environment.yml, rfi_file_monitor/operations/docs/scicataloguer.pango, rfi_file_monitor/operations/scicataloguer.py, setup.cfg, tests/test_data/test_dir/myfile1.txt, tests/test_data/test_dir/myfile2.txt, tests/test_data/testfile.txt, tests/tests.py
Adds the Scicataloguer operation. This fetches most information it needs from the user e.g. hostname, username, password. Uses pyscicat to connect to scicat. It still needs instrument preferences set up to work fully as some features like instrument id are not accessible at the moment without requiring more input from the user. Upsert feature not usable yet because it hasn't been added to pyscicat.
=> Scicat operation
